### ISSUE TITLE
yurtiçi kargo

### ISSUE THREAD

**Issue by garsamba** [teknomavi/Kargo#2]
yurtiçi kargo için bir çalışma yapacakmısınız hocam?

**Comment by GoktugOzturk** [comment]
Planlarımızda vardı. Fakat bu repo'yu kullandığımız projemizdeki geliştirme süreçlerini durdurduk o yüzden herhangi bir timeline veremiyorum.

**Comment by GoktugOzturk** [comment]
Merhaba @garsamba, 

@selahaddinh 'in katkılarıyla servise Yurtiçi Kargo entegrasyonu eklendi.

**Comment by garsamba** [comment]
> Merhaba @garsamba,
> 
> @selahaddinh 'in katkılarıyla servise Yurtiçi Kargo entegrasyonu eklendi.

Keşke kullanım ile alakalı biraz detaylanırma olsaydı 😒

**Comment by GoktugOzturk** [comment]
Ben kendi framework'ümde bu kütüphane üzerinde yazdığım wrapper ile istekleri gönderip alıyorum. Dolayısıyla direkt paylaşabileceğim bir kod yok. 

Kısaca yapman gerekenleri anlatayım; takıldığın bir yer olursa onun üzerinden gideriz.

- `Teknomavi\Kargo\CargoFactory::initServiceProvider` ile kullanacağınız provider'a ait servisi aktifleştiriyorsun. Provider adı ve hesap ayarlarını göndermen gerekiyor.

- Sonra bir tane `Teknomavi\Kargo\Model\Package` oluşturup setXXXX fonksiyonları ile pakete ait bilgileri bu objeye tanımlıyorsun. Bunu da üstte oluşturduğun provider objesine `$provider->addPackage` fonksyionu ile ekliyorsun. Aynı işlemi tekrarlayarak birden fazla paket tanımlayabilirsin.

- Tüm paketleri tanımladıktan sonra `$provider->sendPackages()` ile servise istek gönderip gelen sonuca göre kendi tarafında ilgili işlemleri yapıyorsun.

**Comment by GoktugOzturk** [comment]
https://github.com/teknomavi/Kargo/blob/master/tests/YKTest.php buradaki test dosyasında kullanım örneğini hazırlamış @selahaddinh yurtiçi kargo için. Diğerleri de aynı mantıkla çalışıyor.

**Comment by garsamba** [comment]
Tamamdır teşekkür ediyorum müsait bir zamanda deneyeceğim inşallah.

**Comment by MeKerimKilic** [comment]
kullanımda sadece paketi alıcak kişinin bilgileri yeterli olucakmıdır çünkü package classında hem alıcı hem gönderici fonksiyonları tanımlı ancak kullanımda sadece gönderici bilgileri girilmiş gözüküyor
