### ISSUE TITLE
YÜkleme Sorunu

### ISSUE THREAD

**Issue by msthzn** [teknomavi/Kargo#3]
**Describe the bug**
Merhaba öncelikle teşekkürler hocam ellerinize sağlık. Paketi yüklemeye çalıştığımızda aşağıdaki şekilde bir hata aldık. İyi çalışmalar.

**Additional context**
  Problem 1
    - teknomavi/kargo 2.0.4 requires symfony/options-resolver ^3.4 -> no matching package found.
    - teknomavi/kargo 2.0.3 requires symfony/options-resolver ^3.4 -> no matching package found.
    - teknomavi/kargo 2.0.2 requires symfony/options-resolver ^3.4 -> no matching package found.
    - teknomavi/kargo 2.0.1 requires symfony/options-resolver ^3.4 -> no matching package found.
    - teknomavi/kargo 2.0.0 requires symfony/options-resolver ^3.4 -> no matching package found.
    - Installation request for teknomavi/kargo ^2.0 -> satisfiable by teknomavi/kargo[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by GoktugOzturk** [comment]
option-resolver bağımlığının sürümünü serbest bıraktım. Gördüğüm kadarıyla v3 ve v5 arasında kullanım farklılığı yok. Sorunsuz şekilde çalışması lazım şu anda.

**Comment by msthzn** [comment]
Hocam ilginize teşekkürler. ben normalde symfony framework kullandığım için options resolver vardı o yüzden ben forklayıp composerden options resolver kaldırarak kullandım.
