### ISSUE TITLE
Yurtiçi Kargo Test Ortamı

### ISSUE THREAD

**Issue by selimsaral** [teknomavi/Kargo#8]
Yurtiçi Kargo için direk canlı wsdl url'i kullanılmış, bunu username ve password parametrelerinde olduğu gibi dinamik bir şekilde yapamaz mıyız ? Böylelikle optional olarak test ortamı linkini yazarak test ortamını kullanmış olabiliriz.

**Comment by GoktugOzturk** [comment]
PR için teşekkürler
